years: 
 - 1999
 - 2000
 - 2001
 - 2002
 - 2003
 - 2004
 - 2005
 - 2006
 - 2007
 - 2008
 - 2009
 - 2010
 - 2011
 - 2012 
 - 2013
 - 2014
 - 2015
 - 2016
 - 2017
 - 2018
 - 2019
 - 2020
 - 2021
 - 2022
satellite: modis
sat_image_path: /work/bd1231/tglauch/modis_images_new/
copernicus_path: /work/bd1231/tglauch/copernicus_classification/
out_path: /work/bd1231/tglauch/VPRM_output_modis/
predictions_path: /work/bd1231/tglauch/gpp_eu_modis/
fluxnet_path: /work/bd1231/tglauch/data/
vprm_params_dict: /home/b/b309233/modis.pickle
year_for_fitting: 2014
hvs:
 - [17,2]
 - [17,3]
 - [17,4]
 - [17,5]
 - [18,2]
 - [18,3]
 - [18,4]
 - [18,5]
 - [19,2]
 - [19,3]
 - [19,4]
 - [19,5]
 - [20,2]
 - [20,3]
 - [20,4] 
 - [20,5]
 - [17,1]
 - [18,1]
 - [19,1]
 - [20,1]
