year: 2013
satellite: modis
sat_image_path: /work/bd1231/tglauch/modis_images_new/2013/
copernicus_path: /work/bd1231/tglauch/copernicus_classification/
out_path: /work/bd1231/tglauch/VPRM_input_STILT_EU2_V006_2013/
n_bins_lon: 400
n_bins_lat: 480
lon_min: -15
lon_max: 34.875
lat_min: 33
lat_max: 72.916664
hvs:
 - [17,2]
 - [17,3]
 - [17,4]
 - [17,5]
 - [18,2]
 - [18,3]
 - [18,4]
 - [18,5]
 - [19,2]
 - [19,3]
 - [19,4]
 - [19,5]
 - [20,2]
 - [20,3]
 - [20,4] 
 - [20,5]
 - [17,1]
 - [18,1]
 - [19,1]
 - [20,1]
